expected_answers = {
    "tr_td_tags": [
        {'element_name': 'table', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "jeu de tir (fps)"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "valorant"},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "jeu de tir (battle royal)"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "fortnite"},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "jeu de sport (automobile)"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "forza horizon 5"},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "jeu de sport (football)"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "fifa22"}
    ],
    "th_tag": [
        {'element_name': 'table', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'th', 'element_attr': {}, 'element_text': "catégorie"},
        {'element_name': 'th', 'element_attr': {}, 'element_text': "jeu"},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "jeu de tir (fps)"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "valorant"},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "jeu de tir (battle royal)"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "fortnite"},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "jeu de sport (automobile)"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "forza horizon 5"},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "jeu de sport (football)"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "fifa22"}
    ],
    "span": [
        {'element_name': 'table', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'th', 'element_attr': {"colspan":"2"}, 'element_text': "catégorie"},
        {'element_name': 'th', 'element_attr': {}, 'element_text': "jeu"},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'th', 'element_attr': {"rowspan":"2"}, 'element_text': "jeu de tir"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "fps"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "valorant"},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "battle royal"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "fortnite"},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'th', 'element_attr': {"rowspan":"2"}, 'element_text': "jeu de sport"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "automobile"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "forza horizon 5"},
        {'element_name': 'tr', 'element_attr': {}, 'element_text': ""},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "football"},
        {'element_name': 'td', 'element_attr': {}, 'element_text': "fifa22"}
    ]
}
